version: "3.3"
services:
  web: &WEB
    image: gracepoint/canvas-lms:production
    links:
      - postgres
      - redis
    environment:
      AWS_ACCESS_KEY_ID: foobar
      AWS_SECRET_ACCESS_KEY: foobar
      CANVAS_DOMAIN: localhost
      CANVAS_ENCRYPTION_KEY: fooooooooooooooooooooooobarrrrrrrr
      CANVAS_S3_BUCKET_NAME: some-s3-bucket
      CANVAS_S3_BUCKET_REGION: us-east-1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: canvas
      DB_USER: canvas
      DB_PASSWORD: "password"
      LOG_LEVEL: ERROR
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "80:80"

  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: canvas
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: "password"

  redis:
    image: redis:5.0.9-alpine
