production:
  bucket_name: <%= ENV["CANVAS_S3_BUCKET_NAME"] %>
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["CANVAS_S3_BUCKET_REGION"] %>
